# .github/workflows/ai-responsibility-check.yml

name: Responsible AI Checklist CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  responsibility_checklist:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install necessary dependencies
    - name: Install dependencies
      run: |
        pip install pyyaml

    # Step 4: Validate the checklist from the examples folder
    - name: Validate Checklist
      run: python validate_checklist.py examples/checklist.yaml --project-type machine_learning
