# .github/workflows/ai-responsibility-check.yml

name: Responsible AI Checklist CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'rai_checklist_cli/**'
      - '.github/workflows/ai-responsibility-check.yml'

jobs:
  responsibility_checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate Responsibility Checklist
        run: |
          rai-checklist generate -t default -o responsibility_checklist.md
          cat responsibility_checklist.md

      - name: Upload Checklist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: responsibility-checklist
          path: responsibility_checklist.md